apiVersion: v1
kind: Service
metadata:
  name: {{ include "supercheck.app.fullname" . }}
  labels:
    {{- include "supercheck.labels" . | nindent 4 }}
    {{- include "supercheck.selectorLabels" . | nindent 4 }}
    {{- include "supercheck.componentLabels" "app" | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "supercheck.selectorLabels" . | nindent 4 }}
    {{- include "supercheck.componentLabels" "app" | nindent 4 }}
