apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: supercheck
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - app-deployment.yaml
  - app-service.yaml
  - worker-deployment.yaml
  - worker-service.yaml
  - ingress.yaml
  - pdb-app.yaml
  - pdb-worker.yaml
